FROM docker.io/rockylinux/rockylinux:10
LABEL org.opencontainers.image.base.name="docker.io/rockylinux/rockylinux:10"

ARG DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-euo", "pipefail", "-c"]

RUN dnf upgrade -yq && \
    dnf install -yq --allowerasing \
        curl \
        ca-certificates \
        findutils \
        gnupg \
        tar && \
    bash -c "$(curl -1fsSL 'https://dl.posit.co/public/open/setup.rpm.sh')" && \
    dnf clean all -yq

RUN --mount=type=secret,id=github_token,required=false dnf install -yq \
        quarto-1.9.38 \
        'dnf-command(versionlock)' \
        xz && \
    dnf versionlock add quarto && \
    dnf clean all -yq && \
    GH_TOKEN="$([ -s /run/secrets/github_token ] && cat /run/secrets/github_token)" HOME="/opt/tinytex" CI=true /opt/quarto/bin/quarto install tinytex --no-prompt
