name: 'Setup goss and dgoss'
description: 'Installs goss and dgoss to tools/'
runs:
  using: "composite"
  steps:
    - name: Make tools directory
      shell: bash
      run: mkdir -p tools
    - name: Install goss
      shell: bash
      run: |
        arch=$(uname -m)
        if [ "$arch" = "x86_64" ]; then
            arch="amd64"
        elif [ "$arch" = "aarch64" ]; then
            arch="arm64"
        fi
        curl -fsSL https://github.com/goss-org/goss/releases/latest/download/goss-linux-${arch} -o tools/goss
        chmod +rx tools/goss
    - name: Install dgoss
      shell: bash
      run: |
        curl -fsSL https://github.com/goss-org/goss/releases/latest/download/dgoss -o tools/dgoss
        chmod +rx tools/dgoss
