FROM docker.io/library/ubuntu:22.04
LABEL org.opencontainers.image.base.name="docker.io/library/ubuntu:22.04"

ADD --chmod=750 https://saipittwood.blob.core.windows.net/packages/pti /usr/local/bin/pti

### ARG declarations ###
ARG DEBIAN_FRONTEND=noninteractive
ARG IMAGE_VERSION="{{ Image.Version }}"

### Install Apt Packages ###
COPY {{ VersionPath }}/deps/ubuntu2204_packages.txt /tmp/ubuntu2204_packages.txt
{% if Image.Variant != "Minimal" -%}
COPY {{ VersionPath }}/deps/ubuntu2204_optional_packages.txt /tmp/ubuntu2204_optional_packages.txt
{%- endif %}
RUN pti container syspkg upgrade --dist \
    && pti container syspkg install -f /tmp/ubuntu2204_packages.txt \
    && rm -f /tmp/ubuntu2204_packages.txt \
    {%- if Image.Variant != "Minimal" %}
    && pti container syspkg install -f /tmp/ubuntu2204_optional_packages.txt \
    && rm -f /tmp/ubuntu2204_optional_packages.txt \
    {%- endif %}
    && pti container syspkg clean
