#!/usr/bin/env just --justfile

################
# Variables
CWD := justfile_directory()

################
# Commands

# Install the posit-bakery python project
install:
    poetry install \
        --directory={{ CWD }}

# Build the posit-bakery python project
alias package := build
build:
    poetry build \
        --directory={{ CWD }} \
        --clean

[private]
_pytest *ARGS:
    poetry run -- pytest \
        -n auto \
        --cov=posit_bakery \
        --cov-report=term-missing \
        {{ ARGS }} \
        {{ CWD }}/test/

# Test the posit-bakery python project, skipping slow tests
# Note: Both sets of quotes are required
test *ARGS:
    just _pytest {{ ARGS }} -m "'not slow'"

# Run all tests
test-all *ARGS:
    just _pytest {{ ARGS }}
