#!/usr/bin/env just --justfile

init:
    go mod download
    go install github.com/ctrf-io/go-ctrf-json-reporter/cmd/go-ctrf-json-reporter@latest
    go install github.com/segmentio/golines@latest
    curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.62.2

alias format := lint
lint:
    golines -w .
    golangci-lint run --fix --tests=false

build:
    go build -o out/ -tags test_helper main.go

test:
    go test -v ./...

test-ctrf:
    go test -json ./... | go-ctrf-json-reporter -output ctrf-report.json

clean:
    rm -rf out/
    go clean -cache -testcache -modcache

tidy:
    go mod tidy
