CONFIG_TOML_TPL = """#######################################################################################################################
# BAKERY REPOSITORY CONFIG
#
# This file is used to define global properties for builds inside a repo managed by Posit's Bakery tool.
#######################################################################################################################

# Define properties of the local repository. This information will be used when labeling image builds.
[repository]
url = "{{ repo_url }}"
vendor = "Posit Software, PBC"
maintainer = "docker@posit.co"
authors = []

# Define image registries used by builds in this repository. Images will be tagged appropriately for each registry.
# Logins for private registries should be managed independently of Bakery.
[[registry]]
host = "docker.io"
namespace = "posit"
"""

BASE_MANIFEST_TOML_TPL = """#######################################################################################################################
# BAKERY MANIFEST
#
# This file is used to define nested image builds inside a repo managed by Posit's Bakery tool.
# It is written in TOML format. For more information on TOML, see https://toml.io/en/.
# This file is autogenerated by Bakery. Utilize the Bakery CLI when possible to make changes to this file.
#######################################################################################################################

# Define any variables used by subsequent targets and builds.
[const]
image_name = "base"
os = "{{ image_name }}"

# Define the matrix of builds to be run. This should include all currently supported versions of the image.
# Builds can be automatically generated by the Bakery CLI using `bakery render`.
# [[build]]
# version = "<VERSION>"
# latest = true  # Defaults to False if not specified.

# Define the targets for each build. Each target should be a unique image build contained within each version.
[[target]]
type = "min"
# containerfile = "Containerfile.min"  # Defautls to Containerfile.<type> if not specified.
{% raw %}
# tags = ["{{ os | lower }}{{ build.version | condense }}-min"]  # Default tags for all builds.
# latest_tags = ["{{ os | lower }}-min", "latest-min"]  # Default tags for latest build.
{% endraw %}
# (Optional) define alternative settings for Goss tests for this target.
# [[target.goss]]
{% raw %}
# deps = "{{ build.version }}/deps"  # Defaults to assumed deps path if not specified.
# path = "{{ build.version }}/test"  # Defaults to assumed test path if not specified.
{% endraw %}
# wait = 0  # Defaults to 0 if not specified.
# command = "sleep infinity"  # Defaults to sleep infinity to run if not specified.

[[target]]
type = "std"
# containerfile = "Containerfile.std"  # Defaults to Containerfile.<type> if not specified.
{% raw %}
# tags = ["{{ os | lower }}{{ build.version | condense }}"]  # Default tags for all builds.
# latest_tags = ["{{ os | lower }}", "latest"]  # Default tags for latest build.
{% endraw %}
# (Optional) define alternative settings for Goss tests for this target.
# [[target.goss]]
{% raw %}
# deps = "{{ build.version }}/deps"  # Defaults to assumed deps path if not specified.
# path = "{{ build.version }}/test"  # Defaults to assumed test path if not specified.
{% endraw %}
# wait = 0  # Defaults to 0 if not specified.
# command = "sleep infinity"  # Defaults to sleep infinity to run if not specified.
"""

PRODUCT_MANIFEST_TOML_TPL = """#######################################################################################################################
# BAKERY MANIFEST
#
# This file is used to define nested image builds inside a repo managed by Posit's Bakery tool.
# It is written in TOML format. For more information on TOML, see https://toml.io/en/.
# This file is autogenerated by Bakery. Utilize the Bakery CLI when possible to make changes to this file.
#######################################################################################################################

# Define any variables used by subsequent targets and builds. These are automatically applied as Jinja2 variables to
# builds and targets.
[const]
image_name = "{{ image_name }}"

# Define the matrix of builds to be run. This should include all currently supported versions of the image.
# Builds can be automatically generated by the Bakery CLI using `bakery render`.
# [[build]]
# version = "{{ version }}"
# Define OSes to build for. This should be a list of supported OSes for the image. This setting is expanded to all 
# combinations of build version, OS, and target type. This variable is used for assuming a Containerfile name by
# condensing the full OS name (ex. "Ubuntu 22.04" -> "ubuntu2204") to get `Containerfile.<os>.<type>`. The OS is also
# used for labeling the image builds.
# os = ["Ubuntu 22.04"]
# targets = ["min", "std"]  # Defaults to all targets if not specified.
# latest = true  # Defaults to False if not specified.

# Define the targets for each build. Each target should be a unique image build contained within each version.
[[target]]
type = "min"
# containerfile = "Containerfile.min"  # Defaults to Containerfile.<type> if not specified.
{% raw %}
# tags = ["{{ build.version | safe }}-min", "{{ build.version | clean }}-min"]  # Default tags for all builds.
# latest_tags = ["{{ build.os | condense }}-latest-min", "latest-min"]  # Default tags for latest build.
{% endraw %}
# (Optional) define alternative settings for Goss tests for this target.
# [[target.goss]]
{% raw %}
# deps = "{{ build.version }}/deps"  # Defaults to assumed deps path if not specified.
# path = "{{ build.version }}/test"  # Defaults to assumed test path if not specified.
{% endraw %}
# wait = 0  # Defaults to 0 if not specified.
# command = "sleep infinity"  # Defaults to sleep infinity to run if not specified.

[[target]]
type = "std"
# containerfile = "Containerfile.std"  # Defaults to Containerfile.<type> if not specified.
{% raw %}
# tags = ["{{ build.version | tag_safe }}-{{ build.os | condense }}", "{{ build.version | clean_version }}-{{ build.os | condense }}"]  # Default tags for all builds.
# latest_tags = ["{{ build.os | condense }}-latest", "latest"]  # Default tags for latest build.
{% endraw %}
# (Optional) define alternative settings for Goss tests for this target.
# [[target.goss]]
{% raw %}
# deps = "{{ build.version }}/deps"  # Defaults to assumed deps path if not specified.
# path = "{{ build.version }}/test"  # Defaults to assumed test path if not specified.
{% endraw %}
# wait = 0  # Defaults to 0 if not specified.
# command = "sleep infinity"  # Defaults to sleep infinity to run if not specified.
"""
