// Code generated by mockery v2.50.0. DO NOT EDIT.

package command_mock

import (
	command "pti/system/command"

	mock "github.com/stretchr/testify/mock"
)

// MockShellCommandRunner is an autogenerated mock type for the ShellCommandRunner type
type MockShellCommandRunner struct {
	mock.Mock
}

type MockShellCommandRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShellCommandRunner) EXPECT() *MockShellCommandRunner_Expecter {
	return &MockShellCommandRunner_Expecter{mock: &_m.Mock}
}

// GetArgs provides a mock function with no fields
func (_m *MockShellCommandRunner) GetArgs() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetArgs")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockShellCommandRunner_GetArgs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArgs'
type MockShellCommandRunner_GetArgs_Call struct {
	*mock.Call
}

// GetArgs is a helper method to define mock.On call
func (_e *MockShellCommandRunner_Expecter) GetArgs() *MockShellCommandRunner_GetArgs_Call {
	return &MockShellCommandRunner_GetArgs_Call{Call: _e.mock.On("GetArgs")}
}

func (_c *MockShellCommandRunner_GetArgs_Call) Run(run func()) *MockShellCommandRunner_GetArgs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockShellCommandRunner_GetArgs_Call) Return(_a0 []string) *MockShellCommandRunner_GetArgs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockShellCommandRunner_GetArgs_Call) RunAndReturn(run func() []string) *MockShellCommandRunner_GetArgs_Call {
	_c.Call.Return(run)
	return _c
}

// GetContext provides a mock function with no fields
func (_m *MockShellCommandRunner) GetContext() command.ShellCommandContexter {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetContext")
	}

	var r0 command.ShellCommandContexter
	if rf, ok := ret.Get(0).(func() command.ShellCommandContexter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(command.ShellCommandContexter)
		}
	}

	return r0
}

// MockShellCommandRunner_GetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContext'
type MockShellCommandRunner_GetContext_Call struct {
	*mock.Call
}

// GetContext is a helper method to define mock.On call
func (_e *MockShellCommandRunner_Expecter) GetContext() *MockShellCommandRunner_GetContext_Call {
	return &MockShellCommandRunner_GetContext_Call{Call: _e.mock.On("GetContext")}
}

func (_c *MockShellCommandRunner_GetContext_Call) Run(run func()) *MockShellCommandRunner_GetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockShellCommandRunner_GetContext_Call) Return(_a0 command.ShellCommandContexter) *MockShellCommandRunner_GetContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockShellCommandRunner_GetContext_Call) RunAndReturn(run func() command.ShellCommandContexter) *MockShellCommandRunner_GetContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetEnvVars provides a mock function with no fields
func (_m *MockShellCommandRunner) GetEnvVars() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEnvVars")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockShellCommandRunner_GetEnvVars_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEnvVars'
type MockShellCommandRunner_GetEnvVars_Call struct {
	*mock.Call
}

// GetEnvVars is a helper method to define mock.On call
func (_e *MockShellCommandRunner_Expecter) GetEnvVars() *MockShellCommandRunner_GetEnvVars_Call {
	return &MockShellCommandRunner_GetEnvVars_Call{Call: _e.mock.On("GetEnvVars")}
}

func (_c *MockShellCommandRunner_GetEnvVars_Call) Run(run func()) *MockShellCommandRunner_GetEnvVars_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockShellCommandRunner_GetEnvVars_Call) Return(_a0 []string) *MockShellCommandRunner_GetEnvVars_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockShellCommandRunner_GetEnvVars_Call) RunAndReturn(run func() []string) *MockShellCommandRunner_GetEnvVars_Call {
	_c.Call.Return(run)
	return _c
}

// GetExecutor provides a mock function with no fields
func (_m *MockShellCommandRunner) GetExecutor() command.ShellCommandExecutor {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetExecutor")
	}

	var r0 command.ShellCommandExecutor
	if rf, ok := ret.Get(0).(func() command.ShellCommandExecutor); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(command.ShellCommandExecutor)
		}
	}

	return r0
}

// MockShellCommandRunner_GetExecutor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExecutor'
type MockShellCommandRunner_GetExecutor_Call struct {
	*mock.Call
}

// GetExecutor is a helper method to define mock.On call
func (_e *MockShellCommandRunner_Expecter) GetExecutor() *MockShellCommandRunner_GetExecutor_Call {
	return &MockShellCommandRunner_GetExecutor_Call{Call: _e.mock.On("GetExecutor")}
}

func (_c *MockShellCommandRunner_GetExecutor_Call) Run(run func()) *MockShellCommandRunner_GetExecutor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockShellCommandRunner_GetExecutor_Call) Return(_a0 command.ShellCommandExecutor) *MockShellCommandRunner_GetExecutor_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockShellCommandRunner_GetExecutor_Call) RunAndReturn(run func() command.ShellCommandExecutor) *MockShellCommandRunner_GetExecutor_Call {
	_c.Call.Return(run)
	return _c
}

// GetInheritEnvVars provides a mock function with no fields
func (_m *MockShellCommandRunner) GetInheritEnvVars() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInheritEnvVars")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockShellCommandRunner_GetInheritEnvVars_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInheritEnvVars'
type MockShellCommandRunner_GetInheritEnvVars_Call struct {
	*mock.Call
}

// GetInheritEnvVars is a helper method to define mock.On call
func (_e *MockShellCommandRunner_Expecter) GetInheritEnvVars() *MockShellCommandRunner_GetInheritEnvVars_Call {
	return &MockShellCommandRunner_GetInheritEnvVars_Call{Call: _e.mock.On("GetInheritEnvVars")}
}

func (_c *MockShellCommandRunner_GetInheritEnvVars_Call) Run(run func()) *MockShellCommandRunner_GetInheritEnvVars_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockShellCommandRunner_GetInheritEnvVars_Call) Return(_a0 bool) *MockShellCommandRunner_GetInheritEnvVars_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockShellCommandRunner_GetInheritEnvVars_Call) RunAndReturn(run func() bool) *MockShellCommandRunner_GetInheritEnvVars_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function with no fields
func (_m *MockShellCommandRunner) GetName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockShellCommandRunner_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MockShellCommandRunner_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MockShellCommandRunner_Expecter) GetName() *MockShellCommandRunner_GetName_Call {
	return &MockShellCommandRunner_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *MockShellCommandRunner_GetName_Call) Run(run func()) *MockShellCommandRunner_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockShellCommandRunner_GetName_Call) Return(_a0 string) *MockShellCommandRunner_GetName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockShellCommandRunner_GetName_Call) RunAndReturn(run func() string) *MockShellCommandRunner_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function with no fields
func (_m *MockShellCommandRunner) Run() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockShellCommandRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockShellCommandRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *MockShellCommandRunner_Expecter) Run() *MockShellCommandRunner_Run_Call {
	return &MockShellCommandRunner_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *MockShellCommandRunner_Run_Call) Run(run func()) *MockShellCommandRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockShellCommandRunner_Run_Call) Return(_a0 error) *MockShellCommandRunner_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockShellCommandRunner_Run_Call) RunAndReturn(run func() error) *MockShellCommandRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function with no fields
func (_m *MockShellCommandRunner) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockShellCommandRunner_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockShellCommandRunner_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockShellCommandRunner_Expecter) String() *MockShellCommandRunner_String_Call {
	return &MockShellCommandRunner_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockShellCommandRunner_String_Call) Run(run func()) *MockShellCommandRunner_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockShellCommandRunner_String_Call) Return(_a0 string) *MockShellCommandRunner_String_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockShellCommandRunner_String_Call) RunAndReturn(run func() string) *MockShellCommandRunner_String_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockShellCommandRunner creates a new instance of MockShellCommandRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShellCommandRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShellCommandRunner {
	mock := &MockShellCommandRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
