// Code generated by mockery v2.50.0. DO NOT EDIT.

package command_mock

import mock "github.com/stretchr/testify/mock"

// MockShellCommandContexter is an autogenerated mock type for the ShellCommandContexter type
type MockShellCommandContexter struct {
	mock.Mock
}

type MockShellCommandContexter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShellCommandContexter) EXPECT() *MockShellCommandContexter_Expecter {
	return &MockShellCommandContexter_Expecter{mock: &_m.Mock}
}

// Done provides a mock function with no fields
func (_m *MockShellCommandContexter) Done() <-chan struct{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Done")
	}

	var r0 <-chan struct{}
	if rf, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}

	return r0
}

// MockShellCommandContexter_Done_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Done'
type MockShellCommandContexter_Done_Call struct {
	*mock.Call
}

// Done is a helper method to define mock.On call
func (_e *MockShellCommandContexter_Expecter) Done() *MockShellCommandContexter_Done_Call {
	return &MockShellCommandContexter_Done_Call{Call: _e.mock.On("Done")}
}

func (_c *MockShellCommandContexter_Done_Call) Run(run func()) *MockShellCommandContexter_Done_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockShellCommandContexter_Done_Call) Return(_a0 <-chan struct{}) *MockShellCommandContexter_Done_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockShellCommandContexter_Done_Call) RunAndReturn(run func() <-chan struct{}) *MockShellCommandContexter_Done_Call {
	_c.Call.Return(run)
	return _c
}

// Err provides a mock function with no fields
func (_m *MockShellCommandContexter) Err() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Err")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockShellCommandContexter_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type MockShellCommandContexter_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
func (_e *MockShellCommandContexter_Expecter) Err() *MockShellCommandContexter_Err_Call {
	return &MockShellCommandContexter_Err_Call{Call: _e.mock.On("Err")}
}

func (_c *MockShellCommandContexter_Err_Call) Run(run func()) *MockShellCommandContexter_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockShellCommandContexter_Err_Call) Return(_a0 error) *MockShellCommandContexter_Err_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockShellCommandContexter_Err_Call) RunAndReturn(run func() error) *MockShellCommandContexter_Err_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockShellCommandContexter creates a new instance of MockShellCommandContexter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShellCommandContexter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShellCommandContexter {
	mock := &MockShellCommandContexter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
