// Code generated by mockery v2.50.0. DO NOT EDIT.

//go:build ignore

package command_mock

import mock "github.com/stretchr/testify/mock"

// MockShellCommandExecutor is an autogenerated mock type for the ShellCommandExecutor type
type MockShellCommandExecutor struct {
	mock.Mock
}

type MockShellCommandExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShellCommandExecutor) EXPECT() *MockShellCommandExecutor_Expecter {
	return &MockShellCommandExecutor_Expecter{mock: &_m.Mock}
}

// Start provides a mock function with no fields
func (_m *MockShellCommandExecutor) Start() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockShellCommandExecutor_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockShellCommandExecutor_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockShellCommandExecutor_Expecter) Start() *MockShellCommandExecutor_Start_Call {
	return &MockShellCommandExecutor_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockShellCommandExecutor_Start_Call) Run(run func()) *MockShellCommandExecutor_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockShellCommandExecutor_Start_Call) Return(_a0 error) *MockShellCommandExecutor_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockShellCommandExecutor_Start_Call) RunAndReturn(run func() error) *MockShellCommandExecutor_Start_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function with no fields
func (_m *MockShellCommandExecutor) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockShellCommandExecutor_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockShellCommandExecutor_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockShellCommandExecutor_Expecter) String() *MockShellCommandExecutor_String_Call {
	return &MockShellCommandExecutor_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockShellCommandExecutor_String_Call) Run(run func()) *MockShellCommandExecutor_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockShellCommandExecutor_String_Call) Return(_a0 string) *MockShellCommandExecutor_String_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockShellCommandExecutor_String_Call) RunAndReturn(run func() string) *MockShellCommandExecutor_String_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function with no fields
func (_m *MockShellCommandExecutor) Wait() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockShellCommandExecutor_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockShellCommandExecutor_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
func (_e *MockShellCommandExecutor_Expecter) Wait() *MockShellCommandExecutor_Wait_Call {
	return &MockShellCommandExecutor_Wait_Call{Call: _e.mock.On("Wait")}
}

func (_c *MockShellCommandExecutor_Wait_Call) Run(run func()) *MockShellCommandExecutor_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockShellCommandExecutor_Wait_Call) Return(_a0 error) *MockShellCommandExecutor_Wait_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockShellCommandExecutor_Wait_Call) RunAndReturn(run func() error) *MockShellCommandExecutor_Wait_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockShellCommandExecutor creates a new instance of MockShellCommandExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShellCommandExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShellCommandExecutor {
	mock := &MockShellCommandExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
