FROM docker.io/library/ubuntu:22.04
LABEL org.opencontainers.image.base.name="docker.io/library/ubuntu:22.04"

ARG DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-euo", "pipefail", "-c"]

RUN echo 'Acquire::Retries "3"; Acquire::http::Timeout "30"; Acquire::https::Timeout "30";' > /etc/apt/apt.conf.d/99-retries && \
    apt-get update -yqq --fix-missing && \
    apt-get upgrade -yqq && \
    apt-get dist-upgrade -yqq && \
    apt-get autoremove -yqq --purge && \
    apt-get install -yqq --no-install-recommends \
        curl \
        ca-certificates \
        gnupg \
        tar && \
    apt-get install -yqq --no-install-recommends locales && \
    localedef -i en_US -f UTF-8 en_US.UTF-8 && \
    apt-get clean -yqq && \
    rm -rf /var/lib/apt/lists/*
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

COPY macros-syspkg/1.0.0/deps/packages-1.txt /tmp/packages-1.txt
COPY macros-syspkg/1.0.0/deps/packages-2.txt /tmp/packages-2.txt
RUN apt-get update -yqq && \
    apt-get install -yqq --no-install-recommends \
        jq \
        tree && \
    xargs -a /tmp/packages-1.txt apt-get install -yqq --no-install-recommends && \
    xargs -a /tmp/packages-2.txt apt-get install -yqq --no-install-recommends && \
    apt-get clean -yqq && \
    rm -rf /var/lib/apt/lists/*
