{#-
Below are imports for Bakery's macros. If any are unneeded, they can be removed.
Bakery handles bootstrapping the files into template rendering.
-#}
{%- import "apt.j2" as apt -%}
{%- import "python.j2" as python -%}
{%- import "quarto.j2" as quarto -%}
{%- import "r.j2" as r -%}

# Build Python using uv in a separate stage
{{ python.build_stage(python.build_arg(), prerun=python.declare_build_arg()) }}

FROM docker.io/library/ubuntu:22.04
LABEL org.opencontainers.image.base.name="docker.io/library/ubuntu:22.04"

### ARG declarations ###
ARG DEBIAN_FRONTEND=noninteractive
{{ r.declare_build_arg() }}
{{ python.declare_build_arg() }}
{{ quarto.declare_build_arg() }}

### Install Apt Packages ###
{{ apt.run_setup() }}

COPY {{ Path.Version }}/deps/ubuntu-24.04_packages.txt /tmp/ubuntu-24.04_packages.txt
{{ apt.run_install(files = '/tmp/ubuntu-24.04_packages.txt') }}

# Install Python from previous stage
{{ python.copy_from_build_stage() }}

# Install R
{{ r.run_install(r.build_arg()) }}

# Install Quarto
{{ quarto.run_install(quarto.build_arg(), True) }}
