// Code generated by mockery v2.50.0. DO NOT EDIT.

package syspkg_mock

import (
	syspkg "pti/system/syspkg"

	mock "github.com/stretchr/testify/mock"
)

// MockSystemPackageManager is an autogenerated mock type for the SystemPackageManager type
type MockSystemPackageManager struct {
	mock.Mock
}

type MockSystemPackageManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSystemPackageManager) EXPECT() *MockSystemPackageManager_Expecter {
	return &MockSystemPackageManager_Expecter{mock: &_m.Mock}
}

// Clean provides a mock function with no fields
func (_m *MockSystemPackageManager) Clean() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Clean")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSystemPackageManager_Clean_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clean'
type MockSystemPackageManager_Clean_Call struct {
	*mock.Call
}

// Clean is a helper method to define mock.On call
func (_e *MockSystemPackageManager_Expecter) Clean() *MockSystemPackageManager_Clean_Call {
	return &MockSystemPackageManager_Clean_Call{Call: _e.mock.On("Clean")}
}

func (_c *MockSystemPackageManager_Clean_Call) Run(run func()) *MockSystemPackageManager_Clean_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSystemPackageManager_Clean_Call) Return(_a0 error) *MockSystemPackageManager_Clean_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSystemPackageManager_Clean_Call) RunAndReturn(run func() error) *MockSystemPackageManager_Clean_Call {
	_c.Call.Return(run)
	return _c
}

// GetBin provides a mock function with no fields
func (_m *MockSystemPackageManager) GetBin() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBin")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockSystemPackageManager_GetBin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBin'
type MockSystemPackageManager_GetBin_Call struct {
	*mock.Call
}

// GetBin is a helper method to define mock.On call
func (_e *MockSystemPackageManager_Expecter) GetBin() *MockSystemPackageManager_GetBin_Call {
	return &MockSystemPackageManager_GetBin_Call{Call: _e.mock.On("GetBin")}
}

func (_c *MockSystemPackageManager_GetBin_Call) Run(run func()) *MockSystemPackageManager_GetBin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSystemPackageManager_GetBin_Call) Return(_a0 string) *MockSystemPackageManager_GetBin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSystemPackageManager_GetBin_Call) RunAndReturn(run func() string) *MockSystemPackageManager_GetBin_Call {
	_c.Call.Return(run)
	return _c
}

// GetPackageExtension provides a mock function with no fields
func (_m *MockSystemPackageManager) GetPackageExtension() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPackageExtension")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockSystemPackageManager_GetPackageExtension_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPackageExtension'
type MockSystemPackageManager_GetPackageExtension_Call struct {
	*mock.Call
}

// GetPackageExtension is a helper method to define mock.On call
func (_e *MockSystemPackageManager_Expecter) GetPackageExtension() *MockSystemPackageManager_GetPackageExtension_Call {
	return &MockSystemPackageManager_GetPackageExtension_Call{Call: _e.mock.On("GetPackageExtension")}
}

func (_c *MockSystemPackageManager_GetPackageExtension_Call) Run(run func()) *MockSystemPackageManager_GetPackageExtension_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSystemPackageManager_GetPackageExtension_Call) Return(_a0 string) *MockSystemPackageManager_GetPackageExtension_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSystemPackageManager_GetPackageExtension_Call) RunAndReturn(run func() string) *MockSystemPackageManager_GetPackageExtension_Call {
	_c.Call.Return(run)
	return _c
}

// Install provides a mock function with given fields: list
func (_m *MockSystemPackageManager) Install(list *syspkg.PackageList) error {
	ret := _m.Called(list)

	if len(ret) == 0 {
		panic("no return value specified for Install")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*syspkg.PackageList) error); ok {
		r0 = rf(list)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSystemPackageManager_Install_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Install'
type MockSystemPackageManager_Install_Call struct {
	*mock.Call
}

// Install is a helper method to define mock.On call
//   - list *syspkg.PackageList
func (_e *MockSystemPackageManager_Expecter) Install(list interface{}) *MockSystemPackageManager_Install_Call {
	return &MockSystemPackageManager_Install_Call{Call: _e.mock.On("Install", list)}
}

func (_c *MockSystemPackageManager_Install_Call) Run(run func(list *syspkg.PackageList)) *MockSystemPackageManager_Install_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*syspkg.PackageList))
	})
	return _c
}

func (_c *MockSystemPackageManager_Install_Call) Return(_a0 error) *MockSystemPackageManager_Install_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSystemPackageManager_Install_Call) RunAndReturn(run func(*syspkg.PackageList) error) *MockSystemPackageManager_Install_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: list
func (_m *MockSystemPackageManager) Remove(list *syspkg.PackageList) error {
	ret := _m.Called(list)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*syspkg.PackageList) error); ok {
		r0 = rf(list)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSystemPackageManager_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockSystemPackageManager_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - list *syspkg.PackageList
func (_e *MockSystemPackageManager_Expecter) Remove(list interface{}) *MockSystemPackageManager_Remove_Call {
	return &MockSystemPackageManager_Remove_Call{Call: _e.mock.On("Remove", list)}
}

func (_c *MockSystemPackageManager_Remove_Call) Run(run func(list *syspkg.PackageList)) *MockSystemPackageManager_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*syspkg.PackageList))
	})
	return _c
}

func (_c *MockSystemPackageManager_Remove_Call) Return(_a0 error) *MockSystemPackageManager_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSystemPackageManager_Remove_Call) RunAndReturn(run func(*syspkg.PackageList) error) *MockSystemPackageManager_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with no fields
func (_m *MockSystemPackageManager) Update() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSystemPackageManager_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSystemPackageManager_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
func (_e *MockSystemPackageManager_Expecter) Update() *MockSystemPackageManager_Update_Call {
	return &MockSystemPackageManager_Update_Call{Call: _e.mock.On("Update")}
}

func (_c *MockSystemPackageManager_Update_Call) Run(run func()) *MockSystemPackageManager_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSystemPackageManager_Update_Call) Return(_a0 error) *MockSystemPackageManager_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSystemPackageManager_Update_Call) RunAndReturn(run func() error) *MockSystemPackageManager_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Upgrade provides a mock function with given fields: fullUpgrade
func (_m *MockSystemPackageManager) Upgrade(fullUpgrade bool) error {
	ret := _m.Called(fullUpgrade)

	if len(ret) == 0 {
		panic("no return value specified for Upgrade")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(bool) error); ok {
		r0 = rf(fullUpgrade)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSystemPackageManager_Upgrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upgrade'
type MockSystemPackageManager_Upgrade_Call struct {
	*mock.Call
}

// Upgrade is a helper method to define mock.On call
//   - fullUpgrade bool
func (_e *MockSystemPackageManager_Expecter) Upgrade(fullUpgrade interface{}) *MockSystemPackageManager_Upgrade_Call {
	return &MockSystemPackageManager_Upgrade_Call{Call: _e.mock.On("Upgrade", fullUpgrade)}
}

func (_c *MockSystemPackageManager_Upgrade_Call) Run(run func(fullUpgrade bool)) *MockSystemPackageManager_Upgrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *MockSystemPackageManager_Upgrade_Call) Return(_a0 error) *MockSystemPackageManager_Upgrade_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSystemPackageManager_Upgrade_Call) RunAndReturn(run func(bool) error) *MockSystemPackageManager_Upgrade_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSystemPackageManager creates a new instance of MockSystemPackageManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSystemPackageManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSystemPackageManager {
	mock := &MockSystemPackageManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
