name: 'Setup Bakery'
description: "Installs Posit Bakery tool in Github Actions CI"

inputs:
  version:
    description: "The version of the Posit Bakery tool to install"
    required: false
    default: "main"
  python-version:
    description: "The version of Python to use"
    required: false
    default: "3.x"

runs:
  using: "composite"
  steps:
    - name: Setup uv
      uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78  # v7.6.0

    - name: Setup Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
      with:
        python-version: "${{ inputs.python-version }}"

    - name: Install Bakery
      shell: bash
      run: |
        uv tool install "git+https://github.com/posit-dev/images-shared.git@${{ inputs.version }}#subdirectory=posit-bakery&egg=posit-bakery"
