name: 'Setup Bakery'
description: "Installs Posit Bakery tool in Github Actions CI"

inputs:
  version:
    description: "The version of the Posit Bakery tool to install"
    required: false
    default: "main"
  python-version:
    description: "The version of Python to use"
    required: false
    default: "3.x"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "${{ inputs.python-version }}"

    - name: Install Bakery
      shell: bash
      run: |
        pipx install "git+https://github.com/posit-dev/images-shared.git@${{ inputs.version }}#subdirectory=posit-bakery&egg=posit-bakery"
