FROM docker.io/library/ubuntu:22.04
LABEL org.opencontainers.image.base.name="docker.io/library/ubuntu:22.04"

### ARG declarations ###
ARG DEBIAN_FRONTEND=noninteractive
ARG IMAGE_VERSION="1.0.0"

### Install Apt Packages ###
COPY test-multi/1.0.0/deps/ubuntu2204_packages.txt /tmp/ubuntu2204_packages.txt
RUN apt-get update -yqq && \
    apt-get install -yqq --no-install-recommends $(cat /tmp/ubuntu2204_packages.txt) && \
    rm -f /tmp/ubuntu2204_packages.txt && \
    apt-get clean -yqq && \
    rm -rf /var/lib/apt/lists/*
